  jpa:
    hibernate:
      ddl-auto: update
  datasource :
   username : root
   password : anjani4687
   show-sql : true





eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defualt-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
